name = "boardgameengine"
main = "src/index.ts"
compatibility_date = "2026-08-26"
workers_dev = false
routes = [
  { pattern = "boardgames.planitnow.us/sign-in*", zone_name = "planitnow.us" },
  { pattern = "boardgames.planitnow.us/app*", zone_name = "planitnow.us" },
  { pattern = "boardgames.planitnow.us/auth*", zone_name = "planitnow.us" },
  { pattern = "boardgames.planitnow.us/api*", zone_name = "planitnow.us" }
]

[vars]
EMAIL_FROM = "BoardGameEngine <login@boardgames.planitnow.us>"

[[d1_databases]]
binding = "DB"
database_name = "boardgameengine"
database_id = "replace-after-running-wrangler-d1-create"
migrations_dir = "migrations"
