export type BggPollVotes={best:number;recommended:number;notRecommended:number};
export type BggThing={id:number;type:string;name:string;year:number|null;minPlayers:number;maxPlayers:number;minutes:number;weight:number|null;image:string|null;thumbnail:string|null;categories:{id:number;name:string}[];mechanics:{id:number;name:string}[];expansionIds:number[];polls:Record<string,BggPollVotes>};
export type BggCollectionItem={id:number;collId:string;name:string;subtype:string;own:boolean;forTrade:boolean;wishlist:boolean;wishlistPriority:number|null;rating:number|null};
export type BggSearchResult={id:number;type:string;name:string;year:number|null};
export type BggClientOptions={fetcher?:typeof fetch;wait?:(ms:number)=>Promise<void>;minIntervalMs?:number;now?:()=>number};

const ROOT="https://boardgamegeek.com/xmlapi2/";
const RETRYABLE=new Set([202,429,500,502,503,504]);
const DEFAULT_INTERVAL_MS=5000;
const attr=(text:string,name:string)=>new RegExp(`${name}="([^"]*)"`).exec(text)?.[1]??"";
const decodeXml=(value:string)=>value.replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&quot;/g,'"').replace(/&apos;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&");
const numberValue=(body:string,tag:string)=>{const raw=new RegExp(`<${tag}[^>]*value="([^"]*)"`).exec(body)?.[1];if(raw===undefined||raw==="")return null;const value=Number(raw);return Number.isFinite(value)?value:null};
const textValue=(body:string,tag:string)=>{const raw=new RegExp(`<${tag}\\b[^>]*>([\\s\\S]*?)<\\/${tag}>`).exec(body)?.[1];return raw===undefined?null:decodeXml(raw.trim())};

export function parseThingXml(xml:string):BggThing[]{return [...xml.matchAll(/<item\b([^>]*)>([\s\S]*?)<\/item>/g)].map(match=>{const head=match[1],body=match[2],polls:BggThing["polls"]={};const poll=/<poll[^>]*name="suggested_numplayers"[^>]*>([\s\S]*?)<\/poll>/.exec(body)?.[1]??"";for(const result of poll.matchAll(/<results[^>]*numplayers="([^"]+)"[^>]*>([\s\S]*?)<\/results>/g)){const votes=(label:string)=>Number(new RegExp(`<result[^>]*value="${label}"[^>]*numvotes="(\\d+)"`).exec(result[2])?.[1]??0);polls[result[1]]={best:votes("Best"),recommended:votes("Recommended"),notRecommended:votes("Not Recommended")}}const links=(type:string)=>[...body.matchAll(new RegExp(`<link[^>]*type="${type}"[^>]*>`,`g`))].map(x=>({id:Number(attr(x[0],"id")),name:decodeXml(attr(x[0],"value"))})).filter(x=>Number.isFinite(x.id));const expansionIds=links("boardgameexpansion").map(x=>x.id);return{id:Number(attr(head,"id")),type:attr(head,"type"),name:decodeXml(/<name[^>]*type="primary"[^>]*value="([^"]+)"/.exec(body)?.[1]??""),year:numberValue(body,"yearpublished"),minPlayers:numberValue(body,"minplayers")??0,maxPlayers:numberValue(body,"maxplayers")??0,minutes:numberValue(body,"playingtime")??0,weight:numberValue(body,"averageweight"),image:textValue(body,"image"),thumbnail:textValue(body,"thumbnail"),categories:links("boardgamecategory"),mechanics:links("boardgamemechanic"),expansionIds,polls}})}

export function parseCollectionXml(xml:string):BggCollectionItem[]{return [...xml.matchAll(/<item\b([^>]*)>([\s\S]*?)<\/item>/g)].map(match=>{const head=match[1],body=match[2],status=/<status\b([^>]*)\/?>(?:<\/status>)?/.exec(body)?.[1]??"",ratingRaw=/<rating[^>]*value="([^"]*)"/.exec(body)?.[1]??"";return{id:Number(attr(head,"objectid")),collId:attr(head,"collid"),name:textValue(body,"name")??"",subtype:attr(head,"subtype"),own:attr(status,"own")==="1",forTrade:attr(status,"fortrade")==="1",wishlist:attr(status,"wishlist")==="1",wishlistPriority:(()=>{const value=Number(attr(status,"wishlistpriority"));return Number.isFinite(value)&&value>0?value:null})(),rating:(()=>{const value=Number(ratingRaw);return Number.isFinite(value)?value:null})()}}).filter(item=>Number.isFinite(item.id)&&item.id>0)}

export function parseSearchXml(xml:string):BggSearchResult[]{return [...xml.matchAll(/<item\b([^>]*)>([\s\S]*?)<\/item>/g)].map(match=>({id:Number(attr(match[1],"id")),type:attr(match[1],"type"),name:decodeXml(/<name[^>]*value="([^"]*)"/.exec(match[2])?.[1]??""),year:numberValue(match[2],"yearpublished")})).filter(item=>Number.isFinite(item.id)&&item.id>0)}

export function batches<T>(items:T[],size=20):T[][]{if(size<1||size>20)throw new Error("BGG batches must contain 1-20 items");const out:T[][]=[];for(let i=0;i<items.length;i+=size)out.push(items.slice(i,i+size));return out}

export async function fetchWithBackoff(fetcher:()=>Promise<Response>,wait=(ms:number)=>new Promise<void>(r=>setTimeout(r,ms)),attempts=5,intervalMs=DEFAULT_INTERVAL_MS):Promise<Response>{let last:Response|null=null;for(let i=0;i<attempts;i++){const response=await fetcher();last=response;if(!RETRYABLE.has(response.status))return response;if(i<attempts-1)await wait(intervalMs)}throw new Error(`BGG request remained unavailable after ${attempts} attempts (last status ${last?.status??"unknown"})`)}

export class BggClient{private lastRequestAt=-Infinity;private readonly fetcher:typeof fetch;private readonly wait:(ms:number)=>Promise<void>;private readonly minIntervalMs:number;private readonly now:()=>number;constructor(private readonly token:string,options:BggClientOptions={}){if(!token)throw new Error("BGG API token is not configured");this.fetcher=options.fetcher??fetch;this.wait=options.wait??((ms:number)=>new Promise<void>(r=>setTimeout(r,ms)));this.minIntervalMs=options.minIntervalMs??DEFAULT_INTERVAL_MS;this.now=options.now??Date.now}async collection(username:string,params:Record<string,string|number|boolean>={}):Promise<BggCollectionItem[]>{const query=new URLSearchParams({username,...toParams(params)});return parseCollectionXml(await this.request("collection",query))}async things(ids:number[]):Promise<BggThing[]>{if(!ids.length)return[];if(ids.length>20)throw new Error("BGG Thing requests are limited to 20 IDs");return parseThingXml(await this.request("thing",new URLSearchParams({id:ids.join(","),stats:"1"})))}async search(query:string,exact=false):Promise<BggSearchResult[]>{const params=new URLSearchParams({query,type:"boardgame,boardgameexpansion"});if(exact)params.set("exact","1");return parseSearchXml(await this.request("search",params))}private async request(path:string,params:URLSearchParams):Promise<string>{const elapsed=this.now()-this.lastRequestAt;if(elapsed<this.minIntervalMs)await this.wait(this.minIntervalMs-elapsed);this.lastRequestAt=this.now();const url=`${ROOT}${path}?${params.toString()}`,response=await fetchWithBackoff(()=>this.fetcher(url,{headers:{Authorization:`Bearer ${this.token}`,Accept:"application/xml"}}),this.wait,5,this.minIntervalMs);if(!response.ok)throw new Error(`BGG ${path} request failed with HTTP ${response.status}`);return response.text()}}

function toParams(input:Record<string,string|number|boolean>):Record<string,string>{const out:Record<string,string>={};for(const[key,value]of Object.entries(input))out[key]=String(value);return out}
