import{Hono}from"hono";
import{getCookie}from"hono/cookie";
import{hash}from"./auth";
import{recommend,type Candidate}from"./domain";

type Bindings={DB:D1Database};
type User={id:string;email:string;role:string};
type Variables={user:User};
type PickerBody={players?:number;minutes?:number;minWeight?:number;maxWeight?:number;includeForTrade?:boolean};
type PickerRow={id:number;name:string;sourceName:string|null;minPlayers:number;maxPlayers:number;minutes:number;weight:number;best:number;recommended:number;notRecommended:number};
const api=new Hono<{Bindings:Bindings;Variables:Variables}>();

api.use("*",async(c,next)=>{const token=getCookie(c,"bge_session");if(!token)return c.json({error:"Authentication required"},401);const user=await c.env.DB.prepare("SELECT users.id,users.email,users.role FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.token_hash=? AND users.disabled_at IS NULL").bind(await hash(token)).first<User>();if(!user)return c.json({error:"Authentication required"},401);c.set("user",user);await next()});

api.get("/status",async c=>{const user=c.get("user"),row=await c.env.DB.prepare("SELECT COUNT(DISTINCT ci.bgg_id) owned,COUNT(DISTINCT CASE WHEN g.bgg_fetched_at IS NOT NULL THEN ci.bgg_id END) enriched FROM collection_items ci JOIN games g ON g.id=ci.bgg_id WHERE ci.user_id=? AND ci.own=1").bind(user.id).first<{owned:number;enriched:number}>(),account=await c.env.DB.prepare("SELECT username,last_collection_sync_at lastCollectionSyncAt,last_full_sync_at lastFullSyncAt FROM source_accounts WHERE user_id=? AND provider='bgg'").bind(user.id).first();return c.json({account:account??null,owned:Number(row?.owned??0),enriched:Number(row?.enriched??0)})});

api.post("/recommend",async c=>{const user=c.get("user"),body=await safeJson<PickerBody>(c),input=validatePicker(body);if(!input.ok)return c.json({error:input.error},400);const{players,minutes,minWeight,maxWeight,includeForTrade}=input.value,pollKey=String(players);const rows=await c.env.DB.prepare("SELECT g.id,g.name,MAX(ci.source_name) sourceName,g.min_players minPlayers,g.max_players maxPlayers,g.play_time minutes,g.weight,gp.best_votes best,gp.recommended_votes recommended,gp.not_recommended_votes notRecommended FROM collection_items ci JOIN games g ON g.id=ci.bgg_id JOIN game_polls gp ON gp.bgg_id=g.id AND gp.player_count=? WHERE ci.user_id=? AND ci.own=1 AND (?=1 OR ci.for_trade=0) AND g.bgg_fetched_at IS NOT NULL AND g.min_players IS NOT NULL AND g.max_players IS NOT NULL AND g.play_time IS NOT NULL AND g.weight IS NOT NULL GROUP BY g.id,g.name,g.min_players,g.max_players,g.play_time,g.weight,gp.best_votes,gp.recommended_votes,gp.not_recommended_votes LIMIT 2000").bind(pollKey,user.id,includeForTrade?1:0).all<PickerRow>();const candidates:Candidate[]=rows.results.map(row=>({id:Number(row.id),name:row.name,minPlayers:Number(row.minPlayers),maxPlayers:Number(row.maxPlayers),minutes:Number(row.minutes),weight:Number(row.weight),best:Number(row.best),recommended:Number(row.recommended),notRecommended:Number(row.notRecommended)})),ranked=recommend(candidates,players,minutes,minWeight,maxWeight),sourceNames=new Map(rows.results.map(row=>[Number(row.id),row.sourceName]));const results=ranked.map(item=>formatResult(item,sourceNames.get(item.id)??null,players));return c.json({query:{players,minutes,minWeight,maxWeight,includeForTrade},eligibleCount:candidates.filter(game=>isEligible(game,players,minutes,minWeight,maxWeight)).length,results,relaxations:results.length<5?suggestRelaxations({minutes,minWeight,maxWeight,includeForTrade}):[]})});

export default api;

export function validatePicker(body:Partial<PickerBody>):{ok:true;value:{players:number;minutes:number;minWeight:number;maxWeight:number;includeForTrade:boolean}}|{ok:false;error:string}{const players=Number(body.players),minutes=Number(body.minutes),minWeight=Number(body.minWeight),maxWeight=Number(body.maxWeight);if(!Number.isInteger(players)||players<1||players>20)return{ok:false,error:"Player count must be between 1 and 20"};if(!Number.isFinite(minutes)||minutes<15||minutes>720)return{ok:false,error:"Available time must be between 15 and 720 minutes"};if(!Number.isFinite(minWeight)||!Number.isFinite(maxWeight)||minWeight<0||maxWeight>5||minWeight>maxWeight)return{ok:false,error:"Weight range must stay between 0 and 5"};return{ok:true,value:{players,minutes,minWeight,maxWeight,includeForTrade:body.includeForTrade===true}}}

function isEligible(game:Candidate,players:number,minutes:number,minWeight:number,maxWeight:number){return players>=game.minPlayers&&players<=game.maxPlayers&&game.minutes<=minutes&&game.weight>=minWeight&&game.weight<=maxWeight}
function formatResult(item:ReturnType<typeof recommend>[number],sourceName:string|null,players:number){const total=item.best+item.recommended+item.notRecommended,percent=(value:number)=>total?Math.round(value/total*100):0;return{id:item.id,name:item.name,sourceName:sourceName&&sourceName!==item.name?sourceName:null,players,minutes:item.minutes,weight:item.weight,best:item.best,recommended:item.recommended,notRecommended:item.notRecommended,votes:total,bestPercent:percent(item.best),positivePercent:percent(item.best+item.recommended),notRecommendedPercent:percent(item.notRecommended),confidence:Math.min(1,total/50),score:item.score,warning:item.warning,reason:item.reason}}
function suggestRelaxations(input:{minutes:number;minWeight:number;maxWeight:number;includeForTrade:boolean}){const result:string[]=[];if(input.minutes<720)result.push("Increase available time");if(input.minWeight>0||input.maxWeight<5)result.push("Widen the complexity range");if(!input.includeForTrade)result.push("Include games marked for trade");return result}
async function safeJson<T>(c:{req:{json:()=>Promise<T>}}):Promise<Partial<T>>{try{return await c.req.json()}catch{return{}}}
